/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Card3D(props) {
  const { nodes, materials } = useGLTF('/card.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Card} scale={[0.23, 1.87, 1.28]} />
      <mesh geometry={nodes.Text.geometry} material={materials.Black} position={[0.22, 0.91, -0.16]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.17, 2.32, 1.17]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.Black} position={[0.21, -0.48, 0]} rotation={[-Math.PI, 0, 0]} scale={[-0.09, -1.09, -1]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials.Black} position={[0.21, 1.2, 0.56]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[-0.41, -0.06, -0.41]} />
    </group>
  )
}

useGLTF.preload('/card.gltf')
